name: Send New Year Message
on:
  schedule:
    - cron: "0 0 1 1 *"

  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python_version: "3.10"
      - name: "Install dependencies"
        run: "pip install -r aalto_fuksi_bot/requirements.txt"
      - name: "Run script"
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          THREAD_ID: ${{ secrets.THREAD_ID }}
        run: "python send_message.py happy-new-year"
